import os

RUTA_USUARIOS = os.path.join("datos", "usuarios.json")
RUTA_DENUNCIAS = os.path.join("datos", "denuncias.json")
RUTA_MENSAJES = os.path.join("datos", "mensajes.json")

TIPOS_DENUNCIA = ["Aseo y Ornato", "Transito Vial", "Delito"]
ESTADOS_DENUNCIA = ["Recibida", "En Proceso", "Resuelta", "Rechazada"]
PROVINCIAS = [
	"Azuay",
	"Bolivar",
	"Canar",
	"Carchi",
	"Chimborazo",
	"Cotopaxi",
	"El Oro",
	"Esmeraldas",
	"Galapagos",
	"Guayas",
	"Imbabura",
	"Loja",
	"Los Rios",
	"Manabi",
	"Morona Santiago",
	"Napo",
	"Orellana",
	"Pastaza",
	"Pichincha",
	"Santa Elena",
	"Santo Domingo de los Tsachilas",
	"Sucumbios",
	"Tungurahua",
	"Zamora Chinchipe",
]

CIUDADES_POR_PROVINCIA = {
	"Azuay": [
		"Cuenca",
		"Gualaceo",
		"Paute",
		"Sigsig",
		"Chordeleg",
		"Santa Isabel",
		"Nabon",
		"Ona",
		"Giron",
		"Pucara",
	],
	"Bolivar": [
		"Guaranda",
		"San Miguel",
		"Chillanes",
		"Echeandia",
		"Caluma",
		"Las Naves",
	],
	"Canar": [
		"Azogues",
		"Canar",
		"La Troncal",
		"Biblian",
		"Deleg",
		"El Tambo",
		"Suscal",
	],
	"Carchi": [
		"Tulcan",
		"Montufar",
		"San Pedro de Huaca",
		"Mira",
		"Espejo",
		"Bolivar",
	],
	"Chimborazo": [
		"Riobamba",
		"Guano",
		"Alausi",
		"Colta",
		"Chambo",
		"Chunchi",
		"Cumanda",
		"Guamote",
		"Penipe",
		"Pallatanga",
	],
	"Cotopaxi": [
		"Latacunga",
		"La Mana",
		"Pujili",
		"Salcedo",
		"Saquisili",
		"Sigchos",
	],
	"El Oro": [
		"Machala",
		"Pasaje",
		"Santa Rosa",
		"Huaquillas",
		"Arenillas",
		"El Guabo",
		"Balsas",
		"Chilla",
		"Pinas",
		"Portovelo",
		"Zaruma",
		"Atahualpa",
		"Marcabeli",
		"Las Lajas",
	],
	"Esmeraldas": [
		"Esmeraldas",
		"Atacames",
		"Quininde",
		"Muisne",
		"Rioverde",
		"San Lorenzo",
		"Eloy Alfaro",
	],
	"Galapagos": [
		"San Cristobal",
		"Santa Cruz",
		"Isabela",
	],
	"Guayas": [
		"Guayaquil",
		"Duran",
		"Samborondon",
		"Daule",
		"Milagro",
		"El Triunfo",
		"Naranjal",
		"Naranjito",
		"Yaguachi",
		"Playas",
		"Salitre",
		"Balzar",
		"El Empalme",
		"Pedro Carbo",
		"Santa Lucia",
		"Simon Bolivar",
		"Bucay",
		"Colimes",
	],
	"Imbabura": [
		"Ibarra",
		"Otavalo",
		"Cotacachi",
		"Antonio Ante",
		"Urcuqui",
		"Pimampiro",
	],
	"Loja": [
		"Loja",
		"Catamayo",
		"Macara",
		"Cariamanga",
		"Celica",
		"Paltas",
		"Puyango",
		"Saraguro",
		"Sozoranga",
		"Chaguarpamba",
		"Gonzanama",
		"Olmedo",
		"Quilanga",
		"Espindola",
		"Zapotillo",
	],
	"Los Rios": [
		"Babahoyo",
		"Quevedo",
		"Vinces",
		"Ventanas",
		"Mocache",
		"Montalvo",
		"Palenque",
		"Baba",
		"Urdaneta",
		"Buena Fe",
		"Valencia",
		"Quinsaloma",
	],
	"Manabi": [
		"Portoviejo",
		"Manta",
		"Chone",
		"Montecristi",
		"Jipijapa",
		"Santa Ana",
		"El Carmen",
		"Pedernales",
		"Jama",
		"San Vicente",
		"Rocafuerte",
		"24 de Mayo",
		"Pichincha",
		"Flavio Alfaro",
		"Tosagua",
		"Bolivar",
		"Junin",
		"Olmedo",
		"Sucre",
		"Puerto Lopez",
	],
	"Morona Santiago": [
		"Macas",
		"Gualaquiza",
		"Sucua",
		"Palora",
		"Logrono",
		"San Juan Bosco",
		"Tiwintza",
		"Taisha",
		"Huamboya",
		"Pablo Sexto",
		"Santiago de Mendez",
		"Limon Indanza",
	],
	"Napo": [
		"Tena",
		"Archidona",
		"El Chaco",
		"Quijos",
		"Carlos Julio Arosemena Tola",
	],
	"Orellana": [
		"Francisco de Orellana",
		"La Joya de los Sachas",
		"Loreto",
		"Aguarico",
	],
	"Pastaza": [
		"Puyo",
		"Arajuno",
		"Mera",
		"Santa Clara",
	],
	"Pichincha": [
		"Quito",
		"Cayambe",
		"Mejia",
		"Pedro Moncayo",
		"Ruminahui",
		"San Miguel de los Bancos",
		"Pedro Vicente Maldonado",
		"Puerto Quito",
	],
	"Santa Elena": [
		"Santa Elena",
		"La Libertad",
		"Salinas",
	],
	"Santo Domingo de los Tsachilas": [
		"Santo Domingo",
		"La Concordia",
	],
	"Sucumbios": [
		"Nueva Loja",
		"Shushufindi",
		"Sucumbios",
		"Cuyabeno",
		"Cascales",
		"Gonzalo Pizarro",
		"Putumayo",
	],
	"Tungurahua": [
		"Ambato",
		"Banos",
		"Pelileo",
		"Patate",
		"Pillaro",
		"Mocha",
		"Tisaleo",
		"Quero",
		"Cevallos",
	],
	"Zamora Chinchipe": [
		"Zamora",
		"Yantzaza",
		"Yacuambi",
		"El Pangui",
		"Centinela del Condor",
		"Nangaritza",
		"Paquisha",
		"Chinchipe",
		"Palanda",
	],
}
